### PR TITLE
Added some missing depends for building

### PR DESCRIPTION
**Pull request by grbd**
Recently tried building this in a windows environment
It all appears fine but was just missing a couple of depends probably due to it being so new

### CODE REVIEW

**Comment by Tahul** [comment]
Thank you a lot @grbd!

**Comment by Tahul** [comment]
By the way @grbd, really interested in having your feedback on any parts of the project!

Feel free to open issues and/or PRs!

**Comment by grbd** [comment]
Thanks very much although to be honest I don't know that much when it comes to JS / TS
Although I have been looking at different CSS-In-JS frameworks for use with my own UI CSS I've been working on
So I'll probably be trying that out for that since I favour TS over JS myself

**Comment by Tahul** [comment]
Hey :)

I added your changes in this commit, with you as co-author: https://github.com/Tahul/pinceau/commit/91ebc2263099f60599b355cd6f4f333891715530

Closing this PR, thanks again!

**Pull request closed without merging**
